### ISSUE TITLE
hand keypoint train 

### ISSUE THREAD

**Issue by mingx9527** [CMU-Perceptual-Computing-Lab/openpose_caffe_train#1]
Hi @gineshidalgo99 
Thanks for your sharing sincerely! I try training hand keypoint model on myself dataset, get into trouble: 

### Issue summary
- poseModel.hpp don't define "hand model (only hand21)" that mean the code nonsupport hand train??  

- you share "hand model" in openpose, but in inference it only has right hand, left hand is mirrored to right hand,  is there any benefit to training like this??? 

looking forward to your reply! 
thanks!

**Comment by gineshidalgo99** [comment]
Sorry, hand can only be trained together with BODY_135. I do not have the code for hand standalone, as that was made with https://arxiv.org/abs/1602.00134. Although this code should be modifiable to allow PAF hand-only in theory.
